// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type upfMonitorSessionInfo struct {
	_         structs.HostLayout
	Seid      uint64
	UeIp      uint32
	UpfIp     uint32
	CreatedAt uint64
}

type upfMonitorTrafficCounter struct {
	_         structs.HostLayout
	Packets   uint64
	Bytes     uint64
	Timestamp uint64
}

// loadUpfMonitor returns the embedded CollectionSpec for upfMonitor.
func loadUpfMonitor() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_UpfMonitorBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load upfMonitor: %w", err)
	}

	return spec, err
}

// loadUpfMonitorObjects loads upfMonitor and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*upfMonitorObjects
//	*upfMonitorPrograms
//	*upfMonitorMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadUpfMonitorObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadUpfMonitor()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// upfMonitorSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type upfMonitorSpecs struct {
	upfMonitorProgramSpecs
	upfMonitorMapSpecs
	upfMonitorVariableSpecs
}

// upfMonitorProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type upfMonitorProgramSpecs struct {
	KprobeGtp5gDevXmit   *ebpf.ProgramSpec `ebpf:"kprobe_gtp5g_dev_xmit"`
	KprobeGtp5gEncapRecv *ebpf.ProgramSpec `ebpf:"kprobe_gtp5g_encap_recv"`
	TracepointKfreeSkb   *ebpf.ProgramSpec `ebpf:"tracepoint_kfree_skb"`
}

// upfMonitorMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type upfMonitorMapSpecs struct {
	AgentConfig    *ebpf.MapSpec `ebpf:"agent_config"`
	DropEvents     *ebpf.MapSpec `ebpf:"drop_events"`
	PacketEvents   *ebpf.MapSpec `ebpf:"packet_events"`
	TeidSessionMap *ebpf.MapSpec `ebpf:"teid_session_map"`
	TeidStats      *ebpf.MapSpec `ebpf:"teid_stats"`
	TrafficStats   *ebpf.MapSpec `ebpf:"traffic_stats"`
}

// upfMonitorVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type upfMonitorVariableSpecs struct {
}

// upfMonitorObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadUpfMonitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type upfMonitorObjects struct {
	upfMonitorPrograms
	upfMonitorMaps
	upfMonitorVariables
}

func (o *upfMonitorObjects) Close() error {
	return _UpfMonitorClose(
		&o.upfMonitorPrograms,
		&o.upfMonitorMaps,
	)
}

// upfMonitorMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadUpfMonitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type upfMonitorMaps struct {
	AgentConfig    *ebpf.Map `ebpf:"agent_config"`
	DropEvents     *ebpf.Map `ebpf:"drop_events"`
	PacketEvents   *ebpf.Map `ebpf:"packet_events"`
	TeidSessionMap *ebpf.Map `ebpf:"teid_session_map"`
	TeidStats      *ebpf.Map `ebpf:"teid_stats"`
	TrafficStats   *ebpf.Map `ebpf:"traffic_stats"`
}

func (m *upfMonitorMaps) Close() error {
	return _UpfMonitorClose(
		m.AgentConfig,
		m.DropEvents,
		m.PacketEvents,
		m.TeidSessionMap,
		m.TeidStats,
		m.TrafficStats,
	)
}

// upfMonitorVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadUpfMonitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type upfMonitorVariables struct {
}

// upfMonitorPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadUpfMonitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type upfMonitorPrograms struct {
	KprobeGtp5gDevXmit   *ebpf.Program `ebpf:"kprobe_gtp5g_dev_xmit"`
	KprobeGtp5gEncapRecv *ebpf.Program `ebpf:"kprobe_gtp5g_encap_recv"`
	TracepointKfreeSkb   *ebpf.Program `ebpf:"tracepoint_kfree_skb"`
}

func (p *upfMonitorPrograms) Close() error {
	return _UpfMonitorClose(
		p.KprobeGtp5gDevXmit,
		p.KprobeGtp5gEncapRecv,
		p.TracepointKfreeSkb,
	)
}

func _UpfMonitorClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed upfmonitor_x86_bpfel.o
var _UpfMonitorBytes []byte
